### ISSUE TITLE
EncodingDetect

### ISSUE THREAD

**Issue by wizos** [dankito/Readability4J#1]
This is great! But can you improve the automatic identification webpage's charset? If the encode is GB2312 or GBK, it will cause error.

**Comment by dankito** [comment]
Do you have any suggestions how to detect the correct encoding? Pull requests are welcome.

As a proposal I could check the HTML header and use that one.
But give me some time, I moved recently and in my new apartment there's still a lot to do.

**Comment by dankito** [comment]
Could you provide me some test data with source html, actual output and expected output?

I checked some sites like http://www.sina.com.cn and http://www.huanqiu.com, and both tell their charset is utf-8.

For example for http://news.sina.com.cn/gov/xlxw/2018-07-17/doc-ihfkffam3728018.shtml Readability4J generates this output: https://dankito.net/test/sina-output.html.

May you only have to wrap the output in

```
<html>
 <head>
  <meta charset="GBK" /> 
 </head>
 <body>
 <!-- output here -->
 </body>
</html>
```

Does it then work as you expect?

**Comment by wizos** [comment]
I subscribe a website is: http://www.shgjj.com/html/zyxw/index.html.
Its output charset is <meta http-equiv=Content-Type content="text/html; charset=gbk"/>.

**Comment by dankito** [comment]
Sorry for letting you wait so long!

I just tried it with this url
    http://www.shgjj.com/html/zyxw/101770.html
and it produced that output
    https://dankito.net/test/shgjj-output.html.

I just wrapped the Readability4J output in

```
<html>
 <head>
  <meta charset="utf-8" /> 
 </head>
 <body>
 <!-- output here -->
 </body>
</html>
```

(not charset="GBK" as suggested in my last post) so that a browser shows the characters correctly.

As I don't understand Chinese that well, what would you say, is the output OK?

**Comment by wizos** [comment]
Thank you, this output is normal!
