### ISSUE TITLE
NullPointerException in ArticleGrabber

### ISSUE THREAD

**Issue by spacecowboy** [dankito/Readability4J#12]
When parsing items in this blog: [Android Developers Blog](http://feeds.feedburner.com/blogspot/hsDu)

I get a NullPointerException at 

https://github.com/dankito/Readability4J/blob/e31b3cfed78ebbcaa75eee59cb669dac41b27f3f/src/main/kotlin/net/dankito/readability4j/processor/ArticleGrabber.kt#L671

because the parent of the topCandidate is null. (Hate that Java nullability).

**Comment by dankito** [comment]
Didn't crash for me with the supplied page, but that definitely an issue, thanks for reporting it to me!

Upcoming version 1.0.6 fixes this.
