### ISSUE TITLE
Possible to provide C library?

### ISSUE THREAD

**Issue by plata** [dankito/Readability4J#22]
build C library (.so) using [Kotlin/Native](https://kotlinlang.org/docs/native-dynamic-libraries.html) and header with e.g. `const char* parse(const char* url, const char* html)`

**Comment by dankito** [comment]
That's not that easily possible, as Readability4j relies heavily on JVM classes and Jsoup, which aren't available at Kotlin/Native. This would require a major rewrite of the whole project.

**Comment by plata** [comment]
Ok, too bad.
