### ISSUE TITLE
how to close debug output?

### ISSUE THREAD

**Issue by wudizhuo** [dankito/Readability4J#3]
Hi, How to config the lib that closes the debug output?  it's a little disturb, thank you.

**Comment by dankito** [comment]
This should only be the case if you're running the tests, not if embedded in your application, doesn't it?

For the tests you can configure the log output in the file `src/test/resources/logback-test.xml`.
Change the log level in the lines

    <root level="DEBUG">
        <appender-ref ref="STDOUT"/>
    </root>

from DEBUG to e. g. INFO.
For documentation see here: https://logback.qos.ch/manual/configuration.html.

If you want to configure logging in your application, Readability4J logs over slf4j.
So you can get and configure Readability4J's log output over any logger that supports slf4j, e. g. logback and log4j.

**Comment by wudizhuo** [comment]
Got it, thanks

**Comment by dankito** [comment]
Updated the README to clarify how logging works.
