### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by vprelovac** [dankito/Readability4J#7]
Hi and thanks for fantastic effort. The speed is phenomenal. 

Do you plan to continue supporting the lib with new commits coming to readability.js project?

Thanks again!

**Comment by dankito** [comment]
From time to time ;).

As I am working on many other projects in parallel - only part of them you can see here on GitHub -, I don't have too much time to take care of this library (as actually it's working and the outcome it produces is really good, so the pressure ain't too high to work further on it).

Would you like to become maintainer of it? I could transfer the ownership to you.

**Comment by vprelovac** [comment]
OK that is very generous giving the effort you put into it. I had something else in mind. Would you be able to contact me at vprelovac@gmail.com to discuss?

**Comment by dankito** [comment]
What could be so secret to not asking it here?

**Comment by vprelovac** [comment]
It is not a secret, just felt it belongs to email, not a github issue board :)
